### ISSUE TITLE
Digital Twin: Wiki 

### ISSUE THREAD

**Issue by AlexandreHannelas** [threefoldfoundation/info_digitaltwin#15]
- [x] Create page and content on how Microsoft, Amazon and all these big tech companies are being hacked and how our solution stands out: https://github.com/threefoldfoundation/info_digitaltwin/issues/14 (@AlexandreHannelas)
- [x] Review Wiki: https://github.com/threefoldfoundation/www_threefold_twin/issues/51 (@despiegk @Sacha96 @AlexandreHannelas)
- [x] DigitalTwin Wiki - Create own DT live chat: https://github.com/threefoldfoundation/info_digitaltwin/issues/12 (@sabrinasadik @AlexandreHannelas) 
- [ ] Digital Twin T&C: https://github.com/threefoldfoundation/home_private/issues/13 (@nbabenko)
